%YAML:1.0
# set path related configurations in path.yaml

# dataset
max_image_index: -1     # set dataset size. you can just run a small piece of the dataset. -1 means all.

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

num_features: 500
num_features_init: 100
num_features_tracking: 100

# some flags.
show_viewer: 1        # if run with no screen, you should set this flag as 0.
loop_flag: 0          # if 1, please set correct voc_file.
show_ground_truth: 1  # if 1, please set correct ground_truth_file.